# Following steps need to be run manually
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh -y
# gh auth login -s admin:org

- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: Add github runner user
  ansible.builtin.user:
    name: github-runner

- name: Create runner directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: github-runner
    group: github-runner

- name: Download runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz
    dest: /actions-runner
    remote_src: yes
    owner: github-runner
    group: github-runner

- name: Insall libicu
  ansible.builtin.dnf:
    name: libicu
    state: installed

- name: Get token
  ansible.builtin.shell: |
    gh api --method POST -H "Accept:application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/roboshopsarthak/actions/runners/registration-token | jq .token
  register: token
  become_user: ec2-user

- name: Register runner
  ansible.builtin.shell: |
    ./config.sh --unattended --url https://github.com/roboshopsarthak --token {{ token.stdout }} --name {{ ansible_hostname }} --runnergroup Default
  become_user: github-runner
  args:
    chdir: /actions-runner
  ignore_errors: yes

- name: Copy Service file
  ansible.builtin.copy:
    src: github-runner.service
    dest: /etc/systemd/system/github-runner.service

- name: Start Service
  ansible.builtin.systemd_service:
    name: github-runner
    daemon-reload: yes
    enabled: yes
    state: restarted